version: '3.8'

services:
  arbitrage-bot:
    build: .
    container_name: crypto-arbitrage-bot
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TRADING_MODE=demo
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3